api {
    web_server: http://localhost:8080
    api_server: http://clearml-apiserver:8008
    files_server: http://clearml-fileserver:8081
    credentials {
        "access_key" = "UST0YK6I9BWCT8DDCAS01LAN2T156J"
        "secret_key" = "AqhRf5od37oGueq4d--SHgICx6Alg0wn7UHxrcIzg01_Pu3EMj1hT5HWnqglsoo1GQ8"
    }
}
