fixed_users {
  guest {
    enabled: false
    default_company: "025315a9321f49f8be07f5ac48fbcf92"
    name: "Guest"
    username: "guest"
    password: "guest"
    allow_endpoints: ["auth.login"]
  }

  dev_user {
    enabled: true
    default_company: "025315a9321f49f8be07f5ac48fbcf92"
    name: "Developer"
    username: "developer"
    password: "developerpass"
    user_key: "DEVACCESSKEY00000001"
    user_secret: "devsecretkey000000000000000001"
  }
}
